#cloud-config
groups:
  - admingroup: [root,sys]
  - cloud-users

users:
  - default
  - name: chintan
    gecos: Chintan
    groups: users
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPmXrTcRnqcoMVb09RNP9XogHPnYAzevUKPzlpSn6odtyw/EGvddaFvbic3YgPNBuHg0nvZPklbxViWRccQcNs7hXK6Xq49WrdQNojFqV5I/9fRCWozR1ZQvnnses13jxXtwJRUoTEv98hRXonAsiJmb6M20E2sWpVGjK2mRs/+Ge6tk4Fcij30LKflpuLexOwHSmgVUdhwIPfE5bBgsJdIb/5HI1Dcd8THo6v2VrpeABTeoOZdH6nswRY5CKHoHYpRkoy1QDOKSA3fYXnenxxf670SQusaxOz01S1f7WmxKFklopS+drr20eb5mzaMTRvrAVCzAkRvPklP0xir1zLltp1u4ql7lf0GjbHVgLLL1eEkQQElwUBFAjmXaxjN3CZ6rSa7P7dOBpjaQCqeycTv3ihq76maUQQpeAxxU+951K6zpSgKXEQPNK0Lxm+9zr1KV26D5zSgeAjY7iUqLpnYYPi4/qBWhqoPdr4grnCUYG9Afz/0DMQByuNpORan1vJF4CCPpRMGnlk1vKqWBpy1b7MPuXhcTyanwea0++UROR/J7pPUTc+WTGcZHmN9Sh8CPyGVZazmkn66qJBqAVxdAXbsK/mQDd9mBNQk7BUkCOMR3mMIcBUWbBXmIKWROqxkSYvIJIJVDGqobsiwqq9SnfYXe65Ot51wa+pdScrjw== chintan@Chintans-MacBook-Air.local
    sudo: ALL=(ALL) NOPASSWD:ALL