apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data
      containers:
      - name: minecraft-server
        image: itzg/minecraft-bedrock-server
        ports:
        - hostPort: 19132
          containerPort: 19132
          protocol: UDP
        env:
        - name: EULA
          value: "true"
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
        volumeMounts:
        - mountPath: "/data"
          name: data
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  selector:
    app: minecraft
  type: NodePort
  ports:
  - targetPort: 19132
    port: 19132
    protocol: UDP
    name: udp
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: minecraft
spec:
  entryPoints:
  - minecraft
  routes:
  - services:
    - name: minecraft
      port: 19132
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/minecraft/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - intel
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi